### ISSUE TITLE
GCN with ODE

### ISSUE THREAD

**Issue by wishforgood** [yrcong/NODIS#5]
Would mind giving some instruction on implementing NODIS with GCN rather than LSTM? It seems that The existing file "ODE.py" in the project only constructs ODE blocks based on LSTM. But as GCN need an adjacent matrix in addition, it seems not possible to simply replace LSTM with GCN ("odeint" function seems to only accept one input tensor). I would appreciate if any suggestion is given.

**Comment by yrcong** [comment]
Well, for the adjacent matrix I remember all elements in the matrix are set to = 1/number of bboxes in the image since these weights cannot be defined manually. I think it is not a good way and the result is also not satisfying. Perhaps you can try to use transformer or multihead attention module (personal advice)...

**Comment by wishforgood** [comment]
OK, that makes sense, thanks for your advice.
