### ISSUE TITLE
Performance drops slightly compared with the reported ones when reproducing "Ours-LSTM"

### ISSUE THREAD

**Issue by wishforgood** [yrcong/NODIS#6]
I followed the training guidance and use the command
`python train_rels.py -m sgcls -order random -b 6 -p 100 -lr 1e-4 -ngpu 1 -ckpt checkpoints/vgdet/vg-24.tar -save_dir checkpoints/ -nepoch 20`
to train the model. But the performance seems to be lower than reported. So I kept refining the model with the following command:
`python train_rels.py -m sgcls -order random -b 6 -p 100 -lr 1e-4 -ngpu 1 -ckpt checkpoints/vgrel-19.tar -save_dir checkpoints/ -nepoch 11 `
I got the checkpoint vgrel-30.tar, which resulted in a performance like the following (I have also done a similar procedure for PREDCLS ):
![image](https://user-images.githubusercontent.com/9963412/125744263-829ae32d-08c8-4302-9e36-37bebf12d3ca.png)
Although the results are close, I still want to make a more precise reproduction. Could you please give some advice on it?

**Comment by yrcong** [comment]
A useful way is training more times and pick the best version. Sometimes the optimization cannot reach the best because of the bad parameter initialization. 

Furthermore, if you want to fine tune the model please select a smaller learning rate. I think the learning rate was already reduced by the scheduler in the first 20 epoch:)

**Comment by wishforgood** [comment]
OK, I will try it. By the way, I actually changed the learning rate to 1e-5 but I described it wrongly. But I guess the learning rate should be even smaller since the learning rate has already been reduced by the scheduler.
